<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>VAMS TROVE - Customer Quotation</title>
<link rel="stylesheet" href="/css/pOCQ.css">
</head>
<body style="background: white;">
	<h1 style="color: #a57c3e" align="center">VAMS TROVE</h1>
	<p align="center">
Flat no-2-1, Mouli Towers, 2nd Floor, 1st Block, 40-14-10E, Chandra Mouli Puram,</p>
<p align="center"> Benz Circle, Vijayawada, Andhra Pradesh 520010</p>
<p align="center"><b>GSTIN: 37ACCFA4901C1ZZ</b></p>
	<hr color="black"/>
	<h2 align="center">Customer Quotation</h2>
	
	<div class="idalign">
		
		<div class="alltables">
		<table align = "center">
		<tr>
					<td><b>Name: </b></td>
					<td> <c:out value="${customerDetails.name}"></c:out> </td>
				</tr>
		<tr>
			<td><b>Mobile: </b></td>
			<td> <c:out value="${customerDetails.mobile}"></c:out> </td>
		</tr>
		
	</table>

		<table align = "center" >
		<tr>
					<td><b> </b></td>
					<td>.</td>
				</tr>
		
		<tr>
			<td><b>Date: </b></td>
			<td> <c:out value="${customerDetails.dateQuotatedOn}"></c:out> </td>
		</tr>
	</table>

	</div>
		
	</div>
	
	
	
	<br/><br/>
	<table align="center" class="displaytable">
		<tr align="center">
			<th>Name</th>
			<th>Height (in inches) </th>
			<th>Width (in inches)</th>
			<th>Area (Sq. Foot)</th>
			<th>Quantity</th>
			<th>Material</th>
			<th>Price(per Sq. Ft.) *</th>
			<th>Amount</th>
		</tr>
		<c:forEach items="${allAdded}" var="item">
			<tr>
				<td>${item.name}</td>
				<td>
					<c:if test="${item.height == -1}"> <c:out value="Not Appicable"></c:out> </c:if>
					<c:if test="${item.height != -1}"> <c:out value="${item.height}"></c:out> </c:if>
				</td>
				<td>
					<c:if test="${item.width == -1}"> <c:out value="Not Appicable"></c:out> </c:if>
					<c:if test="${item.width != -1}"> <c:out value="${item.width}"></c:out> </c:if>
				</td>
				<td>
					<c:if test="${item.area == -1}"> <c:out value="Not Appicable"></c:out> </c:if>
					<c:if test="${item.area != -1}"> <c:out value="${item.area}"></c:out> </c:if>
				</td>
				<td>${item.quantity}</td>
				<td>${item.material}</td>
				<td>${item.price}</td>
				<td>${item.minAmount} - ${item.maxAmount}</td>
			</tr>
		</c:forEach>
		
		<tr style="border:0" >
			<td colspan="7" align="right"><b>Estimated Total Range: </b></td>
			<td colspan="1" align="center">Rs. ${mintotal} - Rs. ${maxtotal}</td>
		</tr>
		
	</table>
	<br/>
	<br/>
	<div class="tnc">
		<p>
		This is a sample quotation generated by the customer in the online site to check our pricings, 
		this quotation is only for the reference purpose of customer and can't be used to claim anything. 
	</p>
	<br/>
	<p>
		This is a sample quotation denoting the range that your quotation may vary, to get the perfect prices, 
		contact the designer. Quotations are only valid if there is an authorized signature from the company along with its stamp. 
	</p>
	</div>
	<br/>
	<br/>
	<center><button class="printbutton" onclick="window.print()">Print</button><br><br><br>
	<button class="printbutton"><a href="/">Home</a></button>
	</center>
	<br/>
	<br/>
</body>
</html>